[2025-04-23T17:22:12.475+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T17:21:54.132819+00:00 [queued]>
[2025-04-23T17:22:12.480+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T17:21:54.132819+00:00 [queued]>
[2025-04-23T17:22:12.481+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-23T17:22:12.500+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_data_to_s3_task> on 2025-04-23 17:21:54.132819+00:00
[2025-04-23T17:22:12.510+0000] {standard_task_runner.py:57} INFO - Started process 863 to run task
[2025-04-23T17:22:12.512+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'prayer_times_data_pipeline', 'upload_data_to_s3_task', 'manual__2025-04-23T17:21:54.132819+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/Extract.py', '--cfg-path', '/tmp/tmpl5hgj5o5']
[2025-04-23T17:22:12.514+0000] {standard_task_runner.py:85} INFO - Job 42: Subtask upload_data_to_s3_task
[2025-04-23T17:22:12.607+0000] {task_command.py:416} INFO - Running <TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T17:21:54.132819+00:00 [running]> on host d02bd472f10d
[2025-04-23T17:22:12.802+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prayer_times_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T17:21:54.132819+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T17:21:54.132819+00:00'
[2025-04-23T17:22:12.808+0000] {logging_mixin.py:151} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/utils/context.py:314 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-04-23T17:22:13.726+0000] {Extract.py:74} INFO - Upload successful.
[2025-04-23T17:22:14.300+0000] {Extract.py:74} INFO - Upload successful.
[2025-04-23T17:22:14.302+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-23T17:22:14.308+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prayer_times_data_pipeline, task_id=upload_data_to_s3_task, execution_date=20250423T172154, start_date=20250423T172212, end_date=20250423T172214
[2025-04-23T17:22:14.372+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-23T17:22:14.394+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
