[2025-04-16T16:52:28.259+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-16T16:52:14.650489+00:00 [queued]>
[2025-04-16T16:52:28.265+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-16T16:52:14.650489+00:00 [queued]>
[2025-04-16T16:52:28.266+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-04-16T16:52:28.288+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_data_to_s3_task> on 2025-04-16 16:52:14.650489+00:00
[2025-04-16T16:52:28.295+0000] {standard_task_runner.py:57} INFO - Started process 171 to run task
[2025-04-16T16:52:28.298+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'prayer_times_data_pipeline', 'upload_data_to_s3_task', 'manual__2025-04-16T16:52:14.650489+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/Extract.py', '--cfg-path', '/tmp/tmpd3_w4b1t']
[2025-04-16T16:52:28.300+0000] {standard_task_runner.py:85} INFO - Job 10: Subtask upload_data_to_s3_task
[2025-04-16T16:52:28.333+0000] {task_command.py:416} INFO - Running <TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-16T16:52:14.650489+00:00 [running]> on host d02bd472f10d
[2025-04-16T16:52:28.525+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prayer_times_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T16:52:14.650489+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T16:52:14.650489+00:00'
[2025-04-16T16:52:29.440+0000] {logging_mixin.py:151} INFO - Upload successful.
[2025-04-16T16:52:29.445+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-16T16:52:29.457+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prayer_times_data_pipeline, task_id=upload_data_to_s3_task, execution_date=20250416T165214, start_date=20250416T165228, end_date=20250416T165229
[2025-04-16T16:52:29.515+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-16T16:52:29.526+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
