[2025-04-23T15:25:20.031+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T15:25:05.519800+00:00 [queued]>
[2025-04-23T15:25:20.037+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T15:25:05.519800+00:00 [queued]>
[2025-04-23T15:25:20.037+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-23T15:25:20.052+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_data_to_s3_task> on 2025-04-23 15:25:05.519800+00:00
[2025-04-23T15:25:20.062+0000] {standard_task_runner.py:57} INFO - Started process 481 to run task
[2025-04-23T15:25:20.069+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'prayer_times_data_pipeline', 'upload_data_to_s3_task', 'manual__2025-04-23T15:25:05.519800+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/Extract.py', '--cfg-path', '/tmp/tmpt37ab9nf']
[2025-04-23T15:25:20.071+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask upload_data_to_s3_task
[2025-04-23T15:25:20.104+0000] {task_command.py:416} INFO - Running <TaskInstance: prayer_times_data_pipeline.upload_data_to_s3_task manual__2025-04-23T15:25:05.519800+00:00 [running]> on host d02bd472f10d
[2025-04-23T15:25:20.701+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='prayer_times_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_data_to_s3_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T15:25:05.519800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T15:25:05.519800+00:00'
[2025-04-23T15:25:23.212+0000] {logging_mixin.py:151} INFO - Upload successful.
[2025-04-23T15:25:23.214+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-04-23T15:25:23.221+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prayer_times_data_pipeline, task_id=upload_data_to_s3_task, execution_date=20250423T152505, start_date=20250423T152520, end_date=20250423T152523
[2025-04-23T15:25:23.272+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-04-23T15:25:23.286+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
